version: "3.9"
services:
  db:
    image: mysql:8.4.3
    container_name: hhplus_mysql_container
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database/mysql.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network: